it('visits the app', () => {
  cy.visit('/')
})

describe('Home page', () => {
  beforeEach(() => {
    cy.visit('/')
  })
  it('check keypad buttons', () => {
    cy.get('.components__Button-mu052l-0')
      .contains('0')
      .click()
      .get('.components__Button-mu052l-0')
      .contains('-')
      .click({ force: true })
      .get('.components__Button-mu052l-0')
      .contains('1')
      .click()
      .get('.components__Button-mu052l-0')
      .contains('+')
      .click({ force: true })
      .get('.components__Button-mu052l-0')
      .contains('2')
      .click()
      .get('.components__Button-mu052l-0')
      .contains('*')
      .click({ force: true })
      .get('.components__Button-mu052l-0')
      .contains('3')
      .click()
      .get('.components__Button-mu052l-0')
      .contains('4')
      .click()
      .get('.components__Button-mu052l-0')
      .contains('5')
      .click()
      .get('.components__Button-mu052l-0')
      .contains('6')
      .click()
      .get('.components__Button-mu052l-0')
      .contains('7')
      .click()
      .get('.components__Button-mu052l-0')
      .contains('8')
      .click()
      .get('.components__Button-mu052l-0')
      .contains('9')
      .click()
      .get('.components__Button-mu052l-0')
      .contains('/')
      .click({ force: true })
      .get('.components__Button-mu052l-0')
      .contains('(')
      .click()
      .get('.components__Button-mu052l-0')
      .contains(')')
      .click()
      .get('.components__Display-sc-17khll6-0')
      .contains('0-1+2*3456789/()')
  })
  it('check calculate', () => {
    cy.get('.components__Button-mu052l-0')
      .contains('0')
      .click()
      .get('.components__Button-mu052l-0')
      .contains('-')
      .click({ force: true })
      .get('.components__Button-mu052l-0')
      .contains('1')
      .click()
      .get('.components__Button-mu052l-0')
      .contains('+')
      .click({ force: true })
      .get('.components__Button-mu052l-0')
      .contains('2')
      .click()
      .get('.components__Button-mu052l-0')
      .contains('*')
      .click({ force: true })
      .get('.components__Button-mu052l-0')
      .contains('3')
      .click()
      .get('.components__Button-mu052l-0')
      .contains('/')
      .click({ force: true })
      .get('.components__Button-mu052l-0')
      .contains('(')
      .click()
      .get('.components__Button-mu052l-0')
      .contains('6')
      .click()
      .get('.components__Button-mu052l-0')
      .contains('+')
      .click({ force: true })
      .get('.components__Button-mu052l-0')
      .contains('9')
      .click()
      .get('.components__Button-mu052l-0')
      .contains(')')
      .click()
      .get('.components__Button-mu052l-0')
      .contains('=')
      .click()
      .get('.components__Display-sc-17khll6-0')
      .contains('-0.6')
  })
  it('clear expression', () => {
    cy.get('.components__Button-mu052l-0')
      .contains('0')
      .click()
      .get('.components__Button-mu052l-0')
      .contains('-')
      .click({ force: true })
      .get('.components__Button-mu052l-0')
      .contains('1')
      .click()
      .get('.components__Button-mu052l-0')
      .contains('C')
      .click({ force: true })
      .get('.components__Display-sc-17khll6-0')
      .contains('0')
  })
  it('clear element', () => {
    cy.get('.components__Button-mu052l-0')
      .contains('0')
      .click()
      .get('.components__Button-mu052l-0')
      .contains('-')
      .click({ force: true })
      .get('.components__Button-mu052l-0')
      .contains('1')
      .click()
      .get('.components__Button-mu052l-0')
      .contains('CE')
      .click()
      .get('.components__Display-sc-17khll6-0')
      .contains('0-')
  })
})

describe('Settigns page', () => {
  beforeEach(() => {
    cy.visit('/settigns')
  })

  it('check settigns title', () => {
    cy.get('.components__Title-sc-9qxm5o-1')
      .should('be.visible')
      .contains('Settigns')
  })
  it('check clear all histoty', () => {
    cy.visit('/')
      .get('.components__Button-mu052l-0')
      .contains('9')
      .click()
      .get('.components__Button-mu052l-0')
      .contains('*')
      .click()
      .get('.components__Button-mu052l-0')
      .contains('9')
      .click()
      .get('.components__Button-mu052l-0')
      .contains('=')
      .click()
      .get('.components__HistoryList-sc-1ydwq76-0')
      .should('have.length', 1)
      .visit('/settigns')
      .get('.components__Button-sc-9qxm5o-2')
      .click()
      .visit('/')
      .get('.components__HistoryList-sc-1ydwq76-0')
      .should('have.length', 1)
  })
  it('select theme', () => {
    cy.get('.components__ThemeSelector-sc-9qxm5o-3')
      .select('Light theme')
      .should('have.value', 'light')
      .select('Dark theme')
      .should('have.value', 'dark')
  })
  it('change theme', () => {
    cy.get('.components__ThemeSelector-sc-9qxm5o-3')
      .select('Light theme')
      .should('have.value', 'light')
      .get('.components__Card-sc-9qxm5o-0')
      .should(
        'have.css',
        'background-color',
        'rgb(255, 255, 255)',
      )
      .get('.components__ThemeSelector-sc-9qxm5o-3')
      .select('Dark theme')
      .should('have.value', 'dark')
      .get('.components__Card-sc-9qxm5o-0')
      .should(
        'have.css',
        'background-color',
        'rgb(0, 0, 0)',
      )
  })
})
